switch to paper for compiling
WooMinecraft/WooMinecraft pull request #263
Opened 2022-01-04 19:39 UTC by jerzean

add velocity check/support
Update Readme

>Pull requests should target **master**.
If your pull requests are not ready to be reviewed, please either label it as `WIP` or open a draft pull request.

## General Checks
Place an X in the boxes that you have completed for this pull request.

- [X] I have linked the ticket associated with this pull request.
- [X] I have fully tested my pull request.

## PR Notes
Add some general notes here about what your PR solves for.

2022-01-05 02:20 UTC, JayWood requested changes

2022-01-05 02:20 UTC, JayWood commented on src/main/java/com/plugish/woominecraft/WooMinecraft.java
> +			getLogger().info(Bukkit.getServer().getName());
Repeating usages of `Bukkit.getServer().getName()` let's make this a variable. Keep the code `DRY`

2022-01-05 02:20 UTC, JayWood commented on src/main/java/com/plugish/woominecraft/WooMinecraft.java
> +			if (Bukkit.getServer().getName().equals("CraftBukkit"))
Missing a bracket here?

2022-01-05 02:20 UTC, JayWood commented on src/main/java/com/plugish/woominecraft/WooMinecraft.java
> +					getLogger().severe("BungeeCord: "+Bukkit.spigot().getConfig().getBoolean("settings.bungeecord"));
Given how many `getLogger.xxx` calls we have here, and the depth of the nesting, I'd either like to see this nesting simplified ( by creating separate methods ) or maybe create a logging class entirely and calling it here. Perhaps this is the web developer in me but I'm not used to seeing such deeply nested IF statements.

2022-01-05 02:20 UTC, JayWood commented on src/main/java/com/plugish/woominecraft/WooMinecraft.java
> +					if (!Bukkit.getOnlineMode() && !Bukkit.spigot().getPaperConfig().getBoolean("settings.velocity-support.enabled")) {
Multiple uses of `Bukkit.getOnlineMode()` - needs to be a variable for re-use.

2022-01-05 02:20 UTC, JayWood commented on src/main/java/com/plugish/woominecraft/WooCommand.java
> +            sender.sendMessage(msg);
Just simplify this, no need for a vairable:
`sender.sendMessage( chatPrefix + ChatColor.translateAlternateColorCodes( '&', plugin.getLang( "general.not_authorized" ) ) );`

2022-01-05 02:21 UTC, JayWood commented
Build also failed, need to make sure it passes. Remember you can click on details, then the `the build` link on the resulting page to see full build details.

2022-01-18 14:18 UTC, OverBrave commented
When can this compilation be published?

2022-01-18 20:04 UTC, JayWood commented
When the build is not failing. From what I can tell of the build log I'm getting this:
`[ERROR] /home/travis/build/WooMinecraft/WooMinecraft/src/main/java/com/plugish/woominecraft/WooMinecraft.java:[18,17] error: cannot access Bukkit`

https://app.travis-ci.com/github/WooMinecraft/WooMinecraft/builds/244297003#L710 Not sure why as I wasn't able to see any changes in his code that should have caused this. I'll retarget the branch this week and merge to a feature branch and see if I can fix the issue.

2022-01-21 21:03 UTC, merged